In [1]:
!wget -O drug200.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv

--2024-04-21 04:50:58--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6027 (5.9K) [text/csv]
Saving to: ‘drug200.csv’

drug200.csv         100%[===================>]   5.89K  --.-KB/s    in 0s      

2024-04-21 04:50:58 (1.77 GB/s) - ‘drug200.csv’ saved [6027/6027]



In [2]:
#import basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
import seaborn as sns

In [3]:
#Read the Data
data = pd.read_csv("drug200.csv")
data

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [4]:
print(data.shape)

(200, 6)


In [5]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [7]:
data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [8]:
data.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [9]:
# Null check
print(data.isnull().sum())

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])

In [11]:
data

Age  Sex      BP Cholesterol  Na_to_K   Drug
0     23    0    HIGH        HIGH   25.355  drugY
1     47    1     LOW        HIGH   13.093  drugC
2     47    1     LOW        HIGH   10.114  drugC
3     28    0  NORMAL        HIGH    7.798  drugX
4     61    0     LOW        HIGH   18.043  drugY
..   ...  ...     ...         ...      ...    ...
195   56    0     LOW        HIGH   11.567  drugC
196   16    1     LOW        HIGH   12.006  drugC
197   52    1  NORMAL        HIGH    9.894  drugX
198   23    1  NORMAL      NORMAL   14.020  drugX
199   40    0     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [12]:
data['Sex'].value_counts()

Sex
1    104
0     96
Name: count, dtype: int64

In [14]:
#Selecting Independant and target variables
X= data[['Age','Sex','BP','Cholesterol']]
y = data['Drug']

In [15]:
X

Age  Sex      BP Cholesterol
0     23    0    HIGH        HIGH
1     47    1     LOW        HIGH
2     47    1     LOW        HIGH
3     28    0  NORMAL        HIGH
4     61    0     LOW        HIGH
..   ...  ...     ...         ...
195   56    0     LOW        HIGH
196   16    1     LOW        HIGH
197   52    1  NORMAL        HIGH
198   23    1  NORMAL      NORMAL
199   40    0     LOW      NORMAL

[200 rows x 4 columns]

In [16]:
y

0      drugY
1      drugC
2      drugC
3      drugX
4      drugY
       ...  
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [17]:
X = pd.get_dummies(X)

In [18]:
#Training the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [19]:
X_train

Age  Sex  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
169   20    0     True   False      False              True   
97    56    0     True   False      False              True   
31    74    1     True   False      False              True   
12    43    1    False    True      False              True   
35    46    1    False   False       True             False   
..   ...  ...      ...     ...        ...               ...   
106   22    1    False   False       True              True   
14    50    0    False   False       True              True   
92    29    0     True   False      False              True   
179   67    0    False   False       True              True   
102   28    0    False    True      False              True   

     Cholesterol_NORMAL  
169               False  
97                False  
31                False  
12                False  
35                 True  
..                  ...  
106               False  
14                False  
92                False  
179               False  
102               False  

[140 rows x 7 columns]

In [20]:
y_train

169    drugA
97     drugY
31     drugB
12     drugY
35     drugX
       ...  
106    drugX
14     drugX
92     drugY
179    drugY
102    drugC
Name: Drug, Length: 140, dtype: object

In [21]:
X_test

Age  Sex  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
95    36    1    False    True      False             False   
15    16    0     True   False      False             False   
30    18    0    False   False       True             False   
158   59    0    False    True      False              True   
128   47    1    False    True      False             False   
115   51    1     True   False      False              True   
69    18    0     True   False      False             False   
170   28    0    False   False       True              True   
174   42    1     True   False      False             False   
45    66    0    False   False       True             False   
66    29    1     True   False      False              True   
182   20    0    False    True      False             False   
165   38    1    False    True      False              True   
78    19    0     True   False      False              True   
186   70    1     True   False      False              True   
177   25    1    False   False       True              True   
56    65    1     True   False      False             False   
152   55    1    False   False       True             False   
82    32    0    False    True      False              True   
68    54    1    False   False       True              True   
124   53    0     True   False      False             False   
16    69    1    False    True      False             False   
148   61    0    False    True      False             False   
93    42    0    False    True      False             False   
65    68    0    False   False       True             False   
60    38    0    False    True      False             False   
84    47    0    False    True      False              True   
67    17    1    False   False       True             False   
125   19    0     True   False      False             False   
132   49    1    False    True      False             False   
9     43    1    False    True      False             False   
18    23    1    False    True      False              True   
55    26    0    False    True      False              True   
75    26    1    False    True      False             False   
150   49    1     True   False      False             False   
104   22    1     True   False      False             False   
135   74    1    False    True      False             False   
137   35    0     True   False      False              True   
164   16    1     True   False      False             False   
76    36    0     True   False      False              True   
79    32    0    False    True      False             False   
197   52    1    False   False       True              True   
38    39    0    False   False       True             False   
24    33    0    False    True      False              True   
122   34    1    False   False       True              True   
195   56    0    False    True      False              True   
29    45    1    False    True      False              True   
19    32    0     True   False      False             False   
143   74    1     True   False      False             False   
86    51    0    False   False       True              True   
114   20    0    False   False       True             False   
173   41    0    False    True      False             False   
5     22    0    False   False       True              True   
126   66    1     True   False      False              True   
117   40    0    False   False       True              True   
73    41    0    False   False       True             False   
140   49    1     True   False      False             False   
98    20    1     True   False      False             False   
172   39    0    False   False       True             False   
96    58    0    False    True      False              True   

     Cholesterol_NORMAL  
95                 True  
15                 True  
30                 True  
158               False  
128                True  
115  

In [22]:
y_test

95     drugX
15     drugY
30     drugX
158    drugC
128    drugY
115    drugY
69     drugY
170    drugX
174    drugA
45     drugX
66     drugA
182    drugX
165    drugY
78     drugA
186    drugB
177    drugY
56     drugB
152    drugX
82     drugC
68     drugY
124    drugB
16     drugX
148    drugX
93     drugY
65     drugY
60     drugY
84     drugC
67     drugX
125    drugY
132    drugX
9      drugY
18     drugC
55     drugC
75     drugY
150    drugA
104    drugY
135    drugX
137    drugA
164    drugY
76     drugA
79     drugX
197    drugX
38     drugX
24     drugY
122    drugY
195    drugC
29     drugY
19     drugY
143    drugY
86     drugX
114    drugX
173    drugY
5      drugX
126    drugY
117    drugX
73     drugY
140    drugA
98     drugY
172    drugY
96     drugY
Name: Drug, dtype: object

In [24]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
y_pred = regressor.predict(X_test)
y_pred_train = regressor.predict(X_train)

In [26]:
y_pred

array(['drugX', 'drugY', 'drugX', 'drugY', 'drugY', 'drugY', 'drugY',
       'drugX', 'drugY', 'drugX', 'drugA', 'drugX', 'drugC', 'drugY',
       'drugB', 'drugX', 'drugB', 'drugX', 'drugY', 'drugY', 'drugY',
       'drugY', 'drugY', 'drugY', 'drugX', 'drugY', 'drugY', 'drugX',
       'drugY', 'drugY', 'drugY', 'drugC', 'drugY', 'drugX', 'drugY',
       'drugA', 'drugY', 'drugY', 'drugA', 'drugY', 'drugX', 'drugY',
       'drugX', 'drugY', 'drugX', 'drugY', 'drugC', 'drugY', 'drugB',
       'drugY', 'drugX', 'drugY', 'drugX', 'drugB', 'drugY', 'drugX',
       'drugY', 'drugA', 'drugX', 'drugY'], dtype=object)

In [27]:
y_pred_train

array(['drugY', 'drugY', 'drugB', 'drugC', 'drugX', 'drugY', 'drugX',
       'drugB', 'drugY', 'drugY', 'drugX', 'drugX', 'drugX', 'drugY',
       'drugY', 'drugY', 'drugA', 'drugY', 'drugA', 'drugX', 'drugC',
       'drugY', 'drugY', 'drugY', 'drugA', 'drugY', 'drugY', 'drugY',
       'drugY', 'drugA', 'drugY', 'drugY', 'drugY', 'drugB', 'drugY',
       'drugY', 'drugX', 'drugY', 'drugX', 'drugX', 'drugY', 'drugY',
       'drugB', 'drugY', 'drugX', 'drugY', 'drugY', 'drugY', 'drugX',
       'drugY', 'drugY', 'drugY', 'drugX', 'drugY', 'drugB', 'drugX',
       'drugY', 'drugX', 'drugY', 'drugY', 'drugY', 'drugB', 'drugC',
       'drugA', 'drugY', 'drugY', 'drugY', 'drugY', 'drugY', 'drugX',
       'drugY', 'drugY', 'drugY', 'drugX', 'drugX', 'drugY', 'drugX',
       'drugX', 'drugY', 'drugX', 'drugY', 'drugX', 'drugX', 'drugY',
       'drugY', 'drugY', 'drugC', 'drugY', 'drugY', 'drugY', 'drugY',
       'drugY', 'drugX', 'drugY', 'drugY', 'drugA', 'drugY', 'drugY',
       'drugY', 'dru

In [28]:
#Confusion matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test,y_pred)
print(cm)

[[ 1  0  0  0  6]
 [ 0  2  0  0  1]
 [ 0  0  1  0  5]
 [ 0  0  0 11  7]
 [ 3  2  2  6 13]]


In [29]:
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

0.4666666666666667

In [30]:
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score,recall_score,precision_score,f1_score
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,average_precision_score


In [31]:
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[ 1  0  0  0  6]
 [ 0  2  0  0  1]
 [ 0  0  1  0  5]
 [ 0  0  0 11  7]
 [ 3  2  2  6 13]]


In [32]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

       drugA       0.25      0.14      0.18         7
       drugB       0.50      0.67      0.57         3
       drugC       0.33      0.17      0.22         6
       drugX       0.65      0.61      0.63        18
       drugY       0.41      0.50      0.45        26

    accuracy                           0.47        60
   macro avg       0.43      0.42      0.41        60
weighted avg       0.46      0.47      0.45        60



In [34]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [35]:
y_pred = model.predict(X_test)
y_pred_train = model.predict(X_train)

In [36]:
y_pred

array(['drugX', 'drugY', 'drugX', 'drugY', 'drugY', 'drugB', 'drugY',
       'drugX', 'drugY', 'drugX', 'drugY', 'drugX', 'drugC', 'drugY',
       'drugB', 'drugY', 'drugY', 'drugY', 'drugC', 'drugX', 'drugB',
       'drugY', 'drugY', 'drugX', 'drugX', 'drugX', 'drugC', 'drugX',
       'drugY', 'drugX', 'drugX', 'drugC', 'drugC', 'drugX', 'drugA',
       'drugA', 'drugY', 'drugA', 'drugY', 'drugA', 'drugX', 'drugX',
       'drugX', 'drugC', 'drugY', 'drugY', 'drugY', 'drugA', 'drugB',
       'drugX', 'drugX', 'drugX', 'drugX', 'drugY', 'drugY', 'drugX',
       'drugA', 'drugA', 'drugX', 'drugY'], dtype=object)

In [37]:
y_pred_train

array(['drugA', 'drugY', 'drugB', 'drugY', 'drugX', 'drugY', 'drugY',
       'drugY', 'drugY', 'drugB', 'drugX', 'drugX', 'drugX', 'drugB',
       'drugA', 'drugX', 'drugY', 'drugX', 'drugA', 'drugX', 'drugC',
       'drugA', 'drugA', 'drugA', 'drugA', 'drugB', 'drugB', 'drugA',
       'drugY', 'drugA', 'drugY', 'drugY', 'drugA', 'drugY', 'drugY',
       'drugY', 'drugX', 'drugY', 'drugX', 'drugY', 'drugY', 'drugX',
       'drugB', 'drugX', 'drugY', 'drugA', 'drugC', 'drugY', 'drugX',
       'drugX', 'drugY', 'drugY', 'drugX', 'drugX', 'drugB', 'drugY',
       'drugB', 'drugX', 'drugY', 'drugY', 'drugY', 'drugB', 'drugC',
       'drugA', 'drugY', 'drugY', 'drugY', 'drugA', 'drugX', 'drugX',
       'drugY', 'drugC', 'drugY', 'drugX', 'drugY', 'drugB', 'drugX',
       'drugX', 'drugY', 'drugY', 'drugY', 'drugY', 'drugY', 'drugC',
       'drugB', 'drugX', 'drugC', 'drugA', 'drugY', 'drugA', 'drugA',
       'drugX', 'drugX', 'drugY', 'drugY', 'drugY', 'drugX', 'drugY',
       'drugA', 'dru

In [38]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 4  0  0  0  3]
 [ 0  2  0  0  1]
 [ 0  0  4  0  2]
 [ 0  0  0 13  5]
 [ 3  2  2  9 10]]


In [39]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

       drugA       0.57      0.57      0.57         7
       drugB       0.50      0.67      0.57         3
       drugC       0.67      0.67      0.67         6
       drugX       0.59      0.72      0.65        18
       drugY       0.48      0.38      0.43        26

    accuracy                           0.55        60
   macro avg       0.56      0.60      0.58        60
weighted avg       0.54      0.55      0.54        60



In [40]:
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

0.55

In [50]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, criterion='entropy',random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [51]:
y_pred = model.predict(X_test)

In [52]:
y_pred

array(['drugX', 'drugY', 'drugX', 'drugY', 'drugY', 'drugA', 'drugY',
       'drugX', 'drugY', 'drugX', 'drugY', 'drugX', 'drugC', 'drugY',
       'drugB', 'drugY', 'drugY', 'drugY', 'drugC', 'drugX', 'drugB',
       'drugY', 'drugY', 'drugX', 'drugY', 'drugX', 'drugC', 'drugX',
       'drugY', 'drugX', 'drugX', 'drugC', 'drugC', 'drugX', 'drugA',
       'drugA', 'drugY', 'drugA', 'drugY', 'drugA', 'drugX', 'drugX',
       'drugX', 'drugC', 'drugY', 'drugY', 'drugY', 'drugA', 'drugB',
       'drugX', 'drugX', 'drugX', 'drugX', 'drugB', 'drugY', 'drugX',
       'drugA', 'drugA', 'drugX', 'drugY'], dtype=object)

In [54]:
c_m = confusion_matrix(y_test,y_pred)
print(c_m)

[[ 4  0  0  0  3]
 [ 0  2  0  0  1]
 [ 0  0  4  0  2]
 [ 0  0  0 13  5]
 [ 4  2  2  8 10]]


In [55]:
c_r = classification_report(y_test,y_pred)
print(c_r)

              precision    recall  f1-score   support

       drugA       0.50      0.57      0.53         7
       drugB       0.50      0.67      0.57         3
       drugC       0.67      0.67      0.67         6
       drugX       0.62      0.72      0.67        18
       drugY       0.48      0.38      0.43        26

    accuracy                           0.55        60
   macro avg       0.55      0.60      0.57        60
weighted avg       0.54      0.55      0.54        60



In [56]:
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy


0.55

In [57]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2,p=2,metric='minkowski')
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [59]:
y_pred = model.predict(X_test)

In [60]:
y_pred

array(['drugX', 'drugY', 'drugA', 'drugX', 'drugC', 'drugA', 'drugA',
       'drugX', 'drugY', 'drugX', 'drugY', 'drugA', 'drugA', 'drugA',
       'drugB', 'drugX', 'drugY', 'drugB', 'drugA', 'drugX', 'drugX',
       'drugC', 'drugY', 'drugX', 'drugB', 'drugX', 'drugC', 'drugC',
       'drugA', 'drugC', 'drugX', 'drugC', 'drugA', 'drugA', 'drugA',
       'drugY', 'drugB', 'drugY', 'drugY', 'drugA', 'drugA', 'drugX',
       'drugX', 'drugX', 'drugX', 'drugY', 'drugX', 'drugA', 'drugB',
       'drugX', 'drugA', 'drugC', 'drugX', 'drugY', 'drugY', 'drugX',
       'drugA', 'drugA', 'drugX', 'drugY'], dtype=object)

In [61]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 4  0  0  0  3]
 [ 0  1  0  1  1]
 [ 2  0  2  1  1]
 [ 4  2  3  7  2]
 [ 7  2  2 10  5]]


In [62]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

       drugA       0.24      0.57      0.33         7
       drugB       0.20      0.33      0.25         3
       drugC       0.29      0.33      0.31         6
       drugX       0.37      0.39      0.38        18
       drugY       0.42      0.19      0.26        26

    accuracy                           0.32        60
   macro avg       0.30      0.36      0.31        60
weighted avg       0.36      0.32      0.31        60



In [63]:
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

0.31666666666666665

In [65]:
#SVC
from sklearn.svm import SVC
SVCclassifier = SVC(kernel='linear', max_iter=251)
SVCclassifier.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=251).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


SVC(kernel='linear', max_iter=251)

In [66]:
y_pred = SVCclassifier.predict(X_test)

In [69]:
y_pred

array(['drugY', 'drugA', 'drugY', 'drugC', 'drugY', 'drugY', 'drugA',
       'drugY', 'drugA', 'drugX', 'drugA', 'drugC', 'drugC', 'drugA',
       'drugB', 'drugC', 'drugB', 'drugX', 'drugC', 'drugX', 'drugY',
       'drugX', 'drugX', 'drugY', 'drugX', 'drugY', 'drugY', 'drugX',
       'drugA', 'drugX', 'drugY', 'drugC', 'drugC', 'drugC', 'drugY',
       'drugA', 'drugX', 'drugY', 'drugA', 'drugY', 'drugY', 'drugX',
       'drugX', 'drugC', 'drugY', 'drugC', 'drugY', 'drugY', 'drugB',
       'drugX', 'drugY', 'drugY', 'drugX', 'drugB', 'drugY', 'drugX',
       'drugY', 'drugA', 'drugX', 'drugC'], dtype=object)

In [68]:
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[ 3  0  0  0  4]
 [ 0  2  0  0  1]
 [ 0  0  5  0  1]
 [ 0  0  1 11  6]
 [ 6  2  5  4  9]]


In [70]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

       drugA       0.33      0.43      0.38         7
       drugB       0.50      0.67      0.57         3
       drugC       0.45      0.83      0.59         6
       drugX       0.73      0.61      0.67        18
       drugY       0.43      0.35      0.38        26

    accuracy                           0.50        60
   macro avg       0.49      0.58      0.52        60
weighted avg       0.52      0.50      0.50        60



In [71]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.5

In [73]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [74]:
y_pred = nb.predict(X_test)

In [ ]:
y_pred

In [75]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 7  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 18  0]
 [ 7  3  4 12  0]]


In [76]:
cr = classification_report(y_test,y_pred)
print(cr)


              precision    recall  f1-score   support

       drugA       0.50      1.00      0.67         7
       drugB       0.50      1.00      0.67         3
       drugC       0.60      1.00      0.75         6
       drugX       0.60      1.00      0.75        18
       drugY       0.00      0.00      0.00        26

    accuracy                           0.57        60
   macro avg       0.44      0.80      0.57        60
weighted avg       0.32      0.57      0.41        60



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [77]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.5666666666666667